[package]
name = "tlc-daemon"
version = "0.1.0"
authors = ["Samuel Dolt <samuel@dolt.ch>"]

[dependencies]
rumqtt = {git="https://github.com/Ather-Energy/RuMqtt.git"}
subcmd = "*"
env_logger = "0.3.5"
log = "0.3.6"
toml = "0.2.1"
